language: python

python:
  - 3.5

services:
  - docker

env:
  matrix:
    - SINGLE_TEST_SETUP=Irods3_3_1ServerController
    - SINGLE_TEST_SETUP=Irods4_1_8ServerController
    - SINGLE_TEST_SETUP=Irods4_1_9ServerController

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=testwithirods --cover-inclusive --exclude-test=testwithirods.tests._common.create_tests_for_all_icat_setups --exclude-test=testwithirods.tests._common.IcatTest
after_success:
  - codecov
